DANBOORU_IMAGE_NUM_PER_GALLERY_PAGE = 20
DANBOORU_IMAGE_NUM_PER_JSON = 20
YANDERE_IMAGE_NUM_PER_GALLERY_PAGE = 40
YANDERE_IMAGE_NUM_PER_JSON = 100
KONACHAN_NET_IMAGE_NUM_PER_GALLERY_PAGE = 1  # At least 1 image on each gallery page
KONACHAN_NET_IMAGE_NUM_PER_JSON = 1000
KONACHAN_COM_IMAGE_NUM_PER_GALLERY_PAGE = 21
KONACHAN_COM_IMAGE_NUM_PER_JSON = 999
GELBOORU_IMAGE_NUM_PER_GALLERY_PAGE = 42
GELBOORU_IMAGE_NUM_PER_JSON = 100
MAX_GELBOORU_JSON_PAGE_NUM = 201  # Gelbooru index start from 0, that is actual page num is 0, 1, ..., 200
MAX_SAFEBOORU_JSON_PAGE_NUM = 2001  # Safebooru index start from 0, that is actual page num is 0, 1, ..., 2000

SPECIAL_WEBSITES = ["pximg.net", "pixiv.net", "twitter.com", "x.com", "twimg.com"]
