####
# WARNING: DO NOT EDIT: this code is automatically generated, see overlay_generator/generate_listeners_module.py
####

from enum import Enum


class NOTIFICATIONS(Enum):
	# InvitationNotificationService
	INVITATION_RECEIVED = 0
	INVITATION_SENT = 1
	INVITATION_DELETED = 2
	INVITATION_UPDATED = 3

	# ContactNotificationService
	CONTACT_NEW = 4
	CONTACT_DELETED = 5
	CONTACT_DETAILS_UPDATED = 6
	CONTACT_PHOTO_UPDATED = 7

	# GroupNotificationService
	GROUP_NEW = 8
	GROUP_DELETED = 9
	GROUP_NAME_UPDATED = 10
	GROUP_PHOTO_UPDATED = 11
	GROUP_DESCRIPTION_UPDATED = 12
	GROUP_PENDING_MEMBER_ADDED = 13
	GROUP_PENDING_MEMBER_REMOVED = 14
	GROUP_MEMBER_JOINED = 15
	GROUP_MEMBER_LEFT = 16
	GROUP_OWN_PERMISSIONS_UPDATED = 17
	GROUP_MEMBER_PERMISSIONS_UPDATED = 18
	GROUP_UPDATE_IN_PROGRESS = 19
	GROUP_UPDATE_FINISHED = 20

	# DiscussionNotificationService
	DISCUSSION_NEW = 21
	DISCUSSION_LOCKED = 22
	DISCUSSION_TITLE_UPDATED = 23
	DISCUSSION_SETTINGS_UPDATED = 24

	# MessageNotificationService
	MESSAGE_RECEIVED = 25
	MESSAGE_SENT = 26
	MESSAGE_DELETED = 27
	MESSAGE_BODY_UPDATED = 28
	MESSAGE_UPLOADED = 29
	MESSAGE_DELIVERED = 30
	MESSAGE_READ = 31
	MESSAGE_LOCATION_RECEIVED = 32
	MESSAGE_LOCATION_SENT = 33
	MESSAGE_LOCATION_SHARING_START = 34
	MESSAGE_LOCATION_SHARING_UPDATE = 35
	MESSAGE_LOCATION_SHARING_END = 36
	MESSAGE_REACTION_ADDED = 37
	MESSAGE_REACTION_UPDATED = 38
	MESSAGE_REACTION_REMOVED = 39

	# AttachmentNotificationService
	ATTACHMENT_RECEIVED = 40
	ATTACHMENT_UPLOADED = 41

	# CallNotificationService
	CALL_INCOMING_CALL = 42
	CALL_RINGING = 43
	CALL_ACCEPTED = 44
	CALL_DECLINED = 45
	CALL_BUSY = 46
	CALL_ENDED = 47
		
