def plane_expr(pt, dir): ...
def plane_expr_by3pt(pt1, pt2, pt3): ...
def plane_expr_bylpt(line_expr, pt): ...
def plane_expr_by2angle(angle_xy, angle_z: int = 0, basept=[0, 0]): ...
def line3d_expr_by2pt(pt1, pt2): ...
def line_plane_intersection(line_expr, plane_expr): ...
def plane_plane_angle(plane1, plane2=[0, 0, 1, 0]): ...
def project_pt2plane(pt, plane): ...
