from _typeshed import Incomplete

def pts_c2o(upoly): ...
def pts_o2c(pts): ...
def remove_repeat(pts): ...
def pts_changestart(pts, startpt): ...
def turnaround(pts): ...
def anti_clockwise(poly): ...
def poly_area(pts, positive_area: bool = False): ...
def dimenset_conbine(dimensets): ...
def add_dimension(pt_cloud, dimenset): ...
def pts_quadrant_select(pts, quadrants=[1, 2, 3, 4]): ...
def pts_quadrant_num(pts): ...
def pt_sum(pts): ...
def pt_wsum(pts, ws): ...
def average_pt(pts): ...
def scale_pts(pts, ratio, basept=[0, 0, 0]): ...
def pt_cloud(x_range=[0, 10, 1], y_range=[0, 10, 1], z_range=[0, 10, 1]): ...
def rotate_pts(pts, angle, basept=[0, 0]): ...
def orientation(pta, ptb, ptc): ...
def get_convex_attrs(pts): ...
def is_convex(upoly): ...
def convex_hull(pts): ...
def pts2convexs(pts): ...
def bound(xs): ...
def bound_2d(pts) -> None: ...
def bound_3d(pts): ...
def aabb(pts): ...
def aabb_3d(pts): ...
def obb_byangle(pts, angle): ...
def obb_min(pts): ...
def angles_of_convexedges(pts): ...
def rotate2onto(pts, max_angle: int = 60): ...
def border_processing(pts, id: str = 'noid'): ...
def replace_border(border, angle: Incomplete | None = None): ...
def lineseg_buffer_convex_abcs(pta, ptb, d): ...
