def pt_poly_relation(pt, pts): ...
def pt_in_poly(pt, pts, edge_include: bool = False): ...
def pt_in_convex_abc(pt, abcs): ...
def pt_on_lineseg(pt, pta, ptb): ...
def perpendicular_bisector(pta, ptb): ...
def poly_l_intersection(pts, abc): ...
def offset_lineseg(pt1, pt2, dir: bool = True, distance: int = 0): ...
def offset_anglept(pt1, pt2, pt3, d, dir: bool = True): ...
def offset_anglept_byangle(pt1, pt2, angle, d, dir: bool = True): ...
def poly_apart_poly(poly1, poly2, edge_include: bool = False): ...
def distance_pt2pt(pt1, pt2): ...
def distance_pt2line(pt, line): ...
def distance_pt2plane(pt, plane): ...
def distance_pt2lineseg(pt, pta, ptb): ...
def distance_lineseg2lineseg(l1pta, l1ptb, l2pta, l2ptb): ...
def distance_pt2poly(pt, pts): ...
def project_pt2line(pt, line): ...
