def pt2d(pt): ...
def pt3d(pt, z: int = 0): ...
def pts_mirror2quadrant(pts, quadrant: int = 1): ...
def pt_mirror2quadrant(pt, quadrant: int = 1): ...
def pt_add(pt1, pt2): ...
def pt_sub(pt1, pt2): ...
def pt_scale(pt, ratio, basept=[0, 0, 0]): ...
def scale_pt(pt, ratio, basept=[0, 0, 0]): ...
def pt_rotate(pt, angle, basept=[0, 0]): ...
def rotate_pt(pt, angle, basept=[0, 0]): ...
def vec_dot(vec1, vec2): ...
def vec_dot_angle(vec1, vec2): ...
def vec3d_cross(vec1, vec2): ...
def vec_mag(vec): ...
def vec_unitize(vec): ...
def angle2vec(angle, r: int = 1): ...
def vec2angle(vec): ...
def vec_proj(vec, dir_vec): ...
def vec_proj_length(vec, dir_vec): ...
def vec_proj_relative_length(vec, dir_unit_vec): ...
def vec_angle_sub(vec, vec0): ...
