# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Performance Domain Types"""

from typing_extensions import TypedDict

"""Run-time execution metric."""
class Metric(TypedDict):
    name: "str"
    """Metric name."""
    value: "float"
    """Metric value."""
