import archigeo.basic.geometry as goo
from _typeshed import Incomplete

ver_path: Incomplete

class Window:
    w: Incomplete
    h: Incomplete
    screen: Incomplete
    clock: Incomplete
    running: bool
    updating: bool
    dt: int
    def __init__(self, w: int = 800, h: int = 800, scale: int = 1) -> None: ...
    def pix_geo_transfer(self, pt): ...
    def frame_begin(self) -> None: ...
    def frame_end(self) -> None: ...
    obj_s3d: Incomplete
    def set_view_byword(self, pos=[0, 0], scale: int = 1, type: str = 'top') -> None: ...
    def set_view_bys3d(self, pos, scale, x_dir=..., y_dir=...) -> None: ...
    def set_view_byangle(self, pos, scale, z_angle, x_angle) -> None: ...
    def edit_drawing_pos(self, pt) -> None: ...
    def edit_drawing_scale(self, scale) -> None: ...
    def set_background(self, color: str = 'white') -> None: ...
    def draw_pt(self, pt, color: str = 'black', size: int = 1) -> None: ...
    def draw_lines(self, pts, color: str = 'black', width: int = 2) -> None: ...
    def draw_poly(self, pts, color: str = 'black', width: int = 2) -> None: ...
    def draw_circle(self, circle: goo.Circle, color: str = 'black', width: int = 2): ...
    def get_mouse_pos(self): ...
    def get_point(self): ...
    def get_mouse_states(self): ...
    def get_key_states(self): ...
    def pause(self, unit: int = 500) -> None: ...
    def color(self, r, g, b, a: int = 255): ...
