# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Cast Domain Types"""

from typing import Optional
from typing_extensions import TypedDict

class Sink(TypedDict):
    name: "str"
    id: "str"
    session: "Optional[str]"
    """Text describing the current session. Present only if there is an active
session on the sink."""
