# Stub file for type hints

import socket
import threading
import queue
import time
from typing import List as _List
from johnsonthy.logging import LOGGER as _LOGGER
from johnsonthy.thread.handler import Runnable as _Runnable, ThreadPoolHandler as _ThreadPoolHandler
from ytsocket.receiver import Receiver as _Receiver
from ytsocket.sender import Sender as _Sender

host: str: ...
port: int: ...
limit: int: ...
interval_time: float: ...
class YTSocket:
    def __init__(self, *args, **kwargs): ...
    def startServer(self, *args, **kwargs): ...
    def stopServer(self, *args, **kwargs): ...

