from EmbeddedML.embeddedML.multiple_linear_regression import MultipleLinearRegression
from EmbeddedML.embeddedML.simple_linear_regression import SimpleLinearRegression
from EmbeddedML.embeddedML.polynomial_regression import PolynomialRegression
from EmbeddedML.embeddedML.logistic_regression import LogisticRegression
from EmbeddedML.embeddedML.knn import KNN
from EmbeddedML.embeddedML.naive_bayes import NaiveBayes
from EmbeddedML.embeddedML.svm import SVM
from EmbeddedML.embeddedML.k_means import K_Means
from EmbeddedML.embeddedML.metrics import Metrics
from EmbeddedML.embeddedML.preprocessing import Preprocessing