# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP DeviceAccess Domain Types"""

from typing_extensions import TypedDict

"""Device request id."""
RequestId = str



"""A device id."""
DeviceId = str



"""Device information displayed in a user prompt to select a device."""
class PromptDevice(TypedDict):
    id: "DeviceId"
    name: "str"
    """Display name as it appears in a device request user prompt."""
