# Generated by Django 5.1.6 on 2025-06-20 05:12

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('saas_base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_owner',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.AddField(
            model_name='tenant',
            name='name',
            field=models.CharField(default='unknown', max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='tenant',
            field=models.ForeignKey(on_delete=models.CASCADE, to=settings.SAAS_TENANT_MODEL),
        ),
    ]
