# coding: utf-8

"""
    Ragagent MCP Gateway

    Advanced AI-powered conversation management system

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ragagent_client.api.mcp_api import MCPApi


class TestMCPApi(unittest.TestCase):
    """MCPApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MCPApi()

    def tearDown(self) -> None:
        pass

    def test_get_mcp_server_spec_mcp_server_spec_get(self) -> None:
        """Test case for get_mcp_server_spec_mcp_server_spec_get

        Get MCP server specification
        """
        pass


if __name__ == '__main__':
    unittest.main()
