# coding: utf-8

"""
    Ragagent MCP Gateway

    Advanced AI-powered conversation management system

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ragagent_client.api.whats_app_api import WhatsAppApi


class TestWhatsAppApi(unittest.TestCase):
    """WhatsAppApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WhatsAppApi()

    def tearDown(self) -> None:
        pass

    def test_webhook_verify_whatsapp_webhook_get(self) -> None:
        """Test case for webhook_verify_whatsapp_webhook_get

        Webhook Verify
        """
        pass

    def test_webhook_whatsapp_webhook_post(self) -> None:
        """Test case for webhook_whatsapp_webhook_post

        Webhook
        """
        pass


if __name__ == '__main__':
    unittest.main()
