"""
v1版本短名称映射
"""

variable_name_to_short_name = {
    'soil_temperature_0_to_10cm': 'st',
    'soil_moisture_0_to_10cm': 'swvl',
    'soil_temperature_10_to_40cm': 'stl2',
    'soil_moisture_10_to_40cm': 'swvl2',
    'soil_temperature_40_to_100cm': 'stl3',
    'soil_moisture_40_to_100cm': 'swvl3',
    'soil_temperature_100_to_200cm': 'stl4',
    'soil_moisture_100_to_200cm': 'swvl4',
    'temperature_2m': 't2m',
    'specific_humidity_2m': 'sh2',
    'dew_point_2m': 'd2m',
    'relative_humidity_2m': 'rh',
    'wind_u_component_10m': 'u10',
    'wind_v_component_10m': 'v10',
    'wind_u_component_20m': 'u20',
    'wind_v_component_20m': 'v20',
    'wind_u_component_30m': 'u30',
    'wind_v_component_30m': 'v30',
    'wind_u_component_40m': 'u40',
    'wind_v_component_40m': 'v40',
    'wind_u_component_50m': 'u50',
    'wind_v_component_50m': 'v50',
    'temperature_80m': 't80',
    'specific_humidity_80m': 'sh80',
    'pressure_80m': 'p80',
    'wind_u_component_80m': 'u80',
    'wind_v_component_80m': 'v80',
    'temperature_100m': 't100',
    'wind_u_component_100m': 'u100',
    'wind_v_component_100m': 'v100',
    'visibility': 'vis',
    'wind_gusts_10m': 'gust',
    'surface_pressure': 'sp',
    'surface_temperature': 'skt',
    'snow_depth': 'snd',
    'precipitation': 'tp',
    'sunshine_duration': 'sunsd',
    'shortwave_radiation': 'dswrf',
    'longwave_radiation_downward': 'dlwrf',
    'shortwave_radiation_upward': 'uswrf',
    'longwave_radiation_upward': 'ulwrf',
    'cloud_cover_low': 'lcc',
    'cloud_cover_mid': 'mcc',
    'cloud_cover_high': 'hcc',
    'cloud_cover': 'tcc',
    'pressure_msl': 'msl',
    'frozen_precipitation_percent': 'cpofp',
    'cape': 'cape',
    'freezing_level_height': 'flh',
    'categorical_freezing_rain': 'cfrzr',
    'lifted_index': 'lftx',
    'latent_heat_flux': 'lhtfl',
    'sensible_heat_flux': 'shtfl',
    'snowfall': 'snow',
    'rain': 'rain',

    'wind_speed_10m': 'ws10m',
    'wind_direction_10m': 'wd10m',
    'wind_speed_20m': 'ws20m',
    'wind_direction_20m': 'wd20m',
    'wind_speed_30m': 'ws30m',
    'wind_direction_30m': 'wd30m',
    'wind_speed_40m': 'ws40m',
    'wind_direction_40m': 'wd40m',
    'wind_speed_50m': 'ws50m',
    'wind_direction_50m': 'wd50m',
    'wind_speed_80m': 'ws80m',
    'wind_direction_80m': 'wd80m',
    'wind_speed_100m': 'ws100m',
    'wind_direction_100m': 'wd100m',

    'vapour_pressure_deficit': 'vpd',
    'wet_bulb_temperature_2m': 'wbt',

    'temperature_80m': 't80m',
    'temperature_100m': 't100m',
}

short_name_to_variable_name = {v: k for k, v in variable_name_to_short_name.items()} 