# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pdata.pb import service_pb2 as pdata_dot_pb_dot_service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pdata/pb/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTableData = channel.unary_stream(
                '/pdata.pb.service.PDataService/GetTableData',
                request_serializer=pdata_dot_pb_dot_service__pb2.GetTableDataRequest.SerializeToString,
                response_deserializer=pdata_dot_pb_dot_service__pb2.GetTableDataResponseChunk.FromString,
                _registered_method=True)


class PDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTableData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTableData': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTableData,
                    request_deserializer=pdata_dot_pb_dot_service__pb2.GetTableDataRequest.FromString,
                    response_serializer=pdata_dot_pb_dot_service__pb2.GetTableDataResponseChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pdata.pb.service.PDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pdata.pb.service.PDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTableData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pdata.pb.service.PDataService/GetTableData',
            pdata_dot_pb_dot_service__pb2.GetTableDataRequest.SerializeToString,
            pdata_dot_pb_dot_service__pb2.GetTableDataResponseChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
