# coding: utf-8

"""
    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import circle.web3.configurations
from circle.web3.configurations.models.create_monitored_tokens_request import CreateMonitoredTokensRequest  # noqa: E501
from circle.web3.configurations.rest import ApiException

class TestCreateMonitoredTokensRequest(unittest.TestCase):
    """CreateMonitoredTokensRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateMonitoredTokensRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateMonitoredTokensRequest`
        """
        model = circle.web3.configurations.models.create_monitored_tokens_request.CreateMonitoredTokensRequest()  # noqa: E501
        if include_optional :
            return CreateMonitoredTokensRequest(
                token_ids = ["a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11"]
            )
        else :
            return CreateMonitoredTokensRequest(
                token_ids = ["a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11"],
        )
        """

    def testCreateMonitoredTokensRequest(self):
        """Test CreateMonitoredTokensRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
