# coding: utf-8

"""
    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import circle.web3.configurations
from circle.web3.configurations.api.developer_account_api import DeveloperAccountApi  # noqa: E501
from circle.web3.configurations.rest import ApiException


class TestDeveloperAccountApi(unittest.TestCase):
    """DeveloperAccountApi unit test stubs"""

    def setUp(self):
        self.api = circle.web3.configurations.api.developer_account_api.DeveloperAccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_entity_config(self):
        """Test case for get_entity_config

        Get configuration for entity  # noqa: E501
        """
        pass

    def test_get_public_key(self):
        """Test case for get_public_key

        Get public key for entity  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
