
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-07-07T13:21:34-0400",
 "dirty": true,
 "error": null,
 "full-revisionid": "d2f2061da9dee0dc6be9ef6c8882496bcea73350",
 "version": "2.65.0rc5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
