# Stub file for type hints

from typing import Optional as _Optional

class Strings:
    @staticmethod
    def to_upper(*args, **kwargs): ...
    @staticmethod
    def to_lower(*args, **kwargs): ...
    @staticmethod
    def to_title(*args, **kwargs): ...
    @staticmethod
    def strip_spaces(*args, **kwargs): ...
    @staticmethod
    def remove_all_spaces(*args, **kwargs): ...
    @staticmethod
    def reverse(*args, **kwargs): ...
    @staticmethod
    def length(*args, **kwargs): ...
    @staticmethod
    def replace(*args, **kwargs): ...
    @staticmethod
    def is_empty(*args, **kwargs): ...
    @staticmethod
    def is_not_empty(*args, **kwargs): ...

