from _typeshed import Incomplete

package_path: Incomplete
ver_path: Incomplete

class FieldGenerator:
    ag: Incomplete
    def __init__(self, wn, hn, unit) -> None: ...
    def add_direct_nomination(self, i, j, angle) -> None: ...
    def add_lineseg_constrain(self, pta, ptb, d) -> None: ...
    def add_poly_constrain(self, pts, d) -> None: ...
    def add_circle_constrain(self, center, d) -> None: ...
    def smooth_grid(self, TIME_LIM: int = 10) -> None: ...
