"""
테스트에 필요한 심볼을 정의합니다.
"""

from typing import List  # 타입 힌팅을 위한 import 추가

def get_binance_symbols_for_backtest() -> List[str]:
    """백테스트용 바이낸스 심볼 리스트를 반환합니다."""
    return [
    "BTCUSDT", "ETHUSDT", "BCHUSDT", "XRPUSDT", "EOSUSDT", "LTCUSDT", "TRXUSDT",
    "ETCUSDT", "LINKUSDT", "XLMUSDT", "ADAUSDT", "DASHUSDT", "ZECUSDT",
    "XTZUSDT", "BNBUSDT", "ATOMUSDT", "ONTUSDT", "IOTAUSDT", "BATUSDT", "VETUSDT",
    "NEOUSDT", "QTUMUSDT", "IOSTUSDT", "THETAUSDT", "ALGOUSDT", "ZILUSDT", "KNCUSDT",
    "ZRXUSDT", "COMPUSDT", "DOGEUSDT", "SXPUSDT", "KAVAUSDT", "BANDUSDT",
    "RLCUSDT", "MKRUSDT", "SNXUSDT", "DOTUSDT", "YFIUSDT", "BALUSDT", "CRVUSDT",
    "TRBUSDT", "RUNEUSDT", "SUSHIUSDT", "EGLDUSDT", "SOLUSDT", "ICXUSDT", "STORJUSDT",
    "BLZUSDT", "UNIUSDT", "AVAXUSDT", "FTMUSDT", "ENJUSDT", "FLMUSDT",
    "KSMUSDT", "NEARUSDT", "AAVEUSDT", "FILUSDT", "RSRUSDT", "LRCUSDT", "BELUSDT",
    "AXSUSDT", "ALPHAUSDT", "ZENUSDT", "SKLUSDT", "GRTUSDT", "1INCHUSDT", "CHZUSDT",
    "SANDUSDT", "ANKRUSDT", "LITUSDT", "RVNUSDT", "SFPUSDT",
    "COTIUSDT", "CHRUSDT", "MANAUSDT", "ALICEUSDT", "HBARUSDT", "ONEUSDT",
    "LINAUSDT", "STMXUSDT", "DENTUSDT", "CELRUSDT", "HOTUSDT", "MTLUSDT", "OGNUSDT",
    "NKNUSDT", "BAKEUSDT", "GTCUSDT", "IOTXUSDT", "C98USDT", "MASKUSDT", "ATAUSDT",
    "DYDXUSDT", "GALAUSDT", "CELOUSDT", "ARUSDT", "ARPAUSDT", "CTSIUSDT",
    "LPTUSDT", "ENSUSDT", "PEOPLEUSDT", "ROSEUSDT", "DUSKUSDT", "FLOWUSDT",
    "JASMYUSDT", "DARUSDT"
]
