from enum import Enum

class Status(Enum):
  SUBMITTING = "SUBMITTING"
  FAILED_SUBMISSION = "FAILED_SUBMISSION"
  QUEUED = "QUEUED"
  RUNNING = "RUNNING"
  COMPLETED = "COMPLETED"
  FAILED = "FAILED"
  CANCELLED = "CANCELLED"
  TIMEOUT = "TIMEOUT"
  OTHER = "OTHER"
  UNKNOWN = "UNKNOWN"

TERMINAL_STATES = {Status.COMPLETED, Status.FAILED, Status.CANCELLED, Status.UNKNOWN, Status.TIMEOUT, Status.FAILED_SUBMISSION}