# Stub file for type hints

import logging.config
import json
import os
from typing import Dict as _Dict
from johnsonthy.helper.paths import Paths as _Paths

class Logger:
    def __init__(self, *args, **kwargs): ...
    def set_custom_logger(self, *args, **kwargs): ...
    def set_default_logger(self, *args, **kwargs): ...
    def get_logger(self, *args, **kwargs): ...
    def _init_logging(self, *args, **kwargs): ...
    def set_level(self, *args, **kwargs): ...
    def debug(self, *args, **kwargs): ...
    def info(self, *args, **kwargs): ...
    def warning(self, *args, **kwargs): ...
    def warn(self, *args, **kwargs): ...
    def error(self, *args, **kwargs): ...
    def critical(self, *args, **kwargs): ...

