from enum import Enum


class FabricItemType(Enum):
    APACHE_AIRFLOW_JOB = "ApacheAirflowJob"
    COPY_JOB = "CopyJob"
    DASHBOARD = "Dashboard"
    DATA_PIPELINE = "DataPipeline"
    DATAFLOW = "Dataflow"
    DATAMART = "Datamart"
    DIGITAL_TWIN_BUILDER = "DigitalTwinBuilder"
    DIGITAL_TWIN_BUILDER_FLOW = "DigitalTwinBuilderFlow"
    ENVIRONMENT = "Environment"
    EVENTHOUSE = "Eventhouse"
    EVENTSTREAM = "Eventstream"
    GRAPHQL_API = "GraphQLApi"
    KQL_DASHBOARD = "KQLDashboard"
    KQL_DATABASE = "KQLDatabase"
    KQL_QUERYSET = "KQLQueryset"
    LAKEHOUSE = "Lakehouse"
    ML_EXPERIMENT = "MLExperiment"
    ML_MODEL = "MLModel"
    MIRRORED_AZURE_DATABRICKS_CATALOG = "MirroredAzureDatabricksCatalog"
    MIRRORED_DATABASE = "MirroredDatabase"
    MIRRORED_WAREHOUSE = "MirroredWarehouse"
    MOUNTED_DATA_FACTORY = "MountedDataFactory"
    NOTEBOOK = "Notebook"
    PAGINATED_REPORT = "PaginatedReport"
    REFLEX = "Reflex"
    REPORT = "Report"
    SQL_DATABASE = "SQLDatabase"
    SQL_ENDPOINT = "SQLEndpoint"
    SEMANTIC_MODEL = "SemanticModel"
    SPARK_JOB_DEFINITION = "SparkJobDefinition"
    VARIABLE_LIBRARY = "VariableLibrary"
    WAREHOUSE = "Warehouse"
    WAREHOUSE_SNAPSHOT = "WarehouseSnapshot"
