/*
Copyright (c) 2025 Amazon.com, Inc. or its affiliates. All Rights Reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Paul Govereau, Sean McLaughlin
*/
#pragma once

// This file is automatically generated from KLR.
// Manual edits to this file will be overwritten.

#include "stdc.h"
#include "region.h"

// KLR Common Abstract Syntax

struct Bool_List {
  struct Bool_List *next;
  bool b;
};

struct Nat_List {
  struct Nat_List *next;
  u32 nat;
};

struct Int_List {
  struct Int_List *next;
  i32 i;
};

struct Float_List {
  struct Float_List *next;
  f32 f;
};

struct String_List {
  struct String_List *next;
  char *s;
};

struct Core_Pos {
  u32 line;
  u32 column;
  u32 lineEnd;
  u32 columnEnd;
};
