# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: t2iapi/biceps/instanceidentifier.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from t2iapi.biceps import codedvalue_pb2 as t2iapi_dot_biceps_dot_codedvalue__pb2
from t2iapi.biceps import localizedtext_pb2 as t2iapi_dot_biceps_dot_localizedtext__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&t2iapi/biceps/instanceidentifier.proto\x12\rt2iapi.biceps\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1et2iapi/biceps/codedvalue.proto\x1a!t2iapi/biceps/localizedtext.proto\"\xe4\x01\n\x15InstanceIdentifierMsg\x12*\n\x04type\x18\x01 \x01(\x0b\x32\x1c.t2iapi.biceps.CodedValueMsg\x12\x38\n\x0fidentifier_name\x18\x02 \x03(\x0b\x32\x1f.t2iapi.biceps.LocalizedTextMsg\x12/\n\troot_attr\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x34\n\x0e\x65xtension_attr\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValueB<\n!com.draeger.medical.t2iapi.bicepsB\x17InstanceIdentifierProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 't2iapi.biceps.instanceidentifier_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.draeger.medical.t2iapi.bicepsB\027InstanceIdentifierProto'
  _globals['_INSTANCEIDENTIFIERMSG']._serialized_start=157
  _globals['_INSTANCEIDENTIFIERMSG']._serialized_end=385
# @@protoc_insertion_point(module_scope)
