"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from langcache.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class SaveCacheEntryResponseTypedDict(TypedDict):
    r"""DTO representing a write cache entry response"""

    entry_id: str
    r"""The ID of the entry that was written"""
    timestamp: datetime
    r"""Response timestamp"""


class SaveCacheEntryResponse(BaseModel):
    r"""DTO representing a write cache entry response"""

    entry_id: Annotated[str, pydantic.Field(alias="entryId")]
    r"""The ID of the entry that was written"""

    timestamp: datetime
    r"""Response timestamp"""
