# Stub file for type hints

import socket
import threading
import queue
import time
from typing import List
from johnsonthy.logging import LOGGER
from johnsonthy.thread.handler import Runnable, ThreadPoolHandler
from ytsocket.receiver import Receiver
from ytsocket.sender import Sender

host: str: ...
port: int: ...
limit: int: ...
interval_time: float: ...
class YTSocket:
    def __init__(self, *args, **kwargs): ...
    def startServer(self, *args, **kwargs): ...
    def stopServer(self, *args, **kwargs): ...

