# Generated by Django 4.2.23 on 2025-07-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_metaview_allow_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metaview',
            name='allow_pop',
        ),
        migrations.AddField(
            model_name='metaview',
            name='allow_order',
            field=models.BooleanField(default=True, verbose_name='排序功能'),
        ),
        migrations.AlterField(
            model_name='metaview',
            name='allow_sort',
            field=models.BooleanField(default=True, verbose_name='移动功能'),
        ),
    ]
