from openagentkit.core.interfaces import BaseChunker as BaseChunker

class CharacterTextChunker(BaseChunker):
    def __init__(self, chunk_size: int = 100, chunk_overlap: int = 0) -> None: ...
    @property
    def chunk_size(self) -> int: ...
    @property
    def chunk_overlap(self) -> int: ...
    def get_chunks(self, text: str) -> list[str]: ...
