def angle_360(angle): ...
def angle_180(angle): ...
def angle_9090(angle): ...
def angle_90(angle, angle_max: int = 90): ...
def angle_byline(line_expr): ...
def angle2xy(angle, r: int = 1): ...
def angle_sub(angle, angle0): ...
def angle2theta(angle): ...
def theta2angle(theta): ...
