def line_expr(pt, angle): ...
def line_expr_byptangle(pt, angle): ...
def line_expr_by2pt(pta, ptb): ...
def line_segment(startpt, endpt, rate): ...
def angle_by2pt(pta, ptb): ...
def angle_by2pt_360(pt0, pt): ...
def angle_by3pt_360(pta, ptb, ptb0): ...
def angle_by4pt_360(pta, ptb, pta0, ptb0): ...
def line_intersection(abc1, abc2): ...
def line_segment_byline(startpt, endpt, abc): ...
