from _typeshed import Incomplete

class AngleGrid:
    unit: Incomplete
    grid: Incomplete
    def __init__(self, grid, unit) -> None: ...
    def print_grid(self) -> None: ...
    def get_gridpt(self, i, j): ...
    def get_angle_byij(self, i, j, rx: int = 0, ry: int = 0): ...
    def get_angle_bypt(self, pt): ...
    def generate_single_path(self, start_pt, step_length: int = 1, start_dir_type: int = 0, count_limit: int = 100): ...
    def generate_cross(self, unit: Incomplete | None = None, cross_length: Incomplete | None = None): ...
    def get_wn(self): ...
    def get_hn(self): ...
    def get_w(self): ...
    def get_h(self): ...
    def pt_in_range(self, pt): ...
