from _typeshed import Incomplete

class Arc2d:
    startpt: Incomplete
    endpt: Incomplete
    start_tangent_angle: Incomplete
    end_tangent_angle: Incomplete
    isline: Incomplete
    cen: Incomplete
    r: Incomplete
    midpt: Incomplete
    def __init__(self, startpt: list, endpt: list, start_tangent_angle: float = None) -> None: ...
    @classmethod
    def by3pt(cls, startpt, endpt, pt_on_arc): ...
    def get_turning(self): ...
    def get_length(self): ...
    def get_area(self): ...
    def get_curvature_byrate(self, rate): ...
    def get_curvature_bylength(self, length): ...
    def radial_move(self, d, lefthand: bool = False) -> None: ...
