from _typeshed import Incomplete

class Arc3d:
    s3d: Incomplete
    arc2d: Incomplete
    isline: Incomplete
    def __init__(self, arc2d, space3d: Incomplete | None = None) -> None: ...
    startpt: Incomplete
    endpt: Incomplete
    midpt: Incomplete
    cen: Incomplete
    r: Incomplete
    def update_world_description(self) -> None: ...
    def get_turning(self): ...
    @classmethod
    def by3pt(cls, startpt, endpt, pt_on_arc): ...
    @classmethod
    def by2pt(cls, startpt, endpt, vec_dir): ...
    def move_under_s3d(self, move_vec) -> None: ...
    def change_s3d_keep_absoulute(self, new_s3d) -> None: ...
    def change_s3d_keep_relative(self, new_s3d) -> None: ...
