from _typeshed import Incomplete

class Circle:
    r: Incomplete
    cen: Incomplete
    def __init__(self, r, cen=[0, 0]) -> None: ...
    def angle2pt(self, angle): ...
    def cross_pts(self, other_cir, tolerance: float = 0.0001): ...
    def cross_pts_old(self, other_cir): ...
