def Point(*args: float): ...
def Vector(*args: float): ...
def Line2dExpr(a: float, b: float, c: float): ...
def Line3dExpr(x0: float, y0: float, z0: float, p: float, q: float, r: float): ...
def PlaneExpr(a: float, b: float, c: float, d: float): ...
