from _typeshed import Incomplete

class Perspective:
    viewpt: Incomplete
    plane_expr: Incomplete
    img_cen: Incomplete
    def __init__(self, viewpt, plane_expr) -> None: ...
    def pt_prespective(self, pt): ...
    def pts_perspective(self, pts): ...
    def pts_perspective_limited(self, pts, r_limit: int = 30): ...
    def pts_singleside(self, pts, type: bool = True): ...
