from _typeshed import Incomplete

class Rect:
    w: Incomplete
    d: Incomplete
    cen: Incomplete
    dir_angle: Incomplete
    def __init__(self, cen, w, d, dir_angle) -> None: ...
    @classmethod
    def by_corner(cls, corner_pt, w, d, dir_angle): ...
    def get_pts(self): ...
    def get_area(self): ...
    def rotate(self, angle, basept: Incomplete | None = None, copy: bool = False): ...
    @classmethod
    def aabb(cls, pts): ...
    @classmethod
    def obb_byangle(cls, pts, dir_angle: float): ...
    @classmethod
    def obb_min(cls, pts: list): ...
