from _typeshed import Incomplete

class Space3d:
    basept: Incomplete
    scale: Incomplete
    x_dir_unit: Incomplete
    y_dir_unit: Incomplete
    z_dir_unit: Incomplete
    dirs: Incomplete
    def __init__(self, basept=[0, 0, 0], x_dir=[1, 0, 0], y_dir_maybe=[0, 1, 0], scale: int = 1) -> None: ...
    def update(self) -> None: ...
    def plane_expr(self): ...
    def pt_relative_describe(self, pt_world): ...
    def vec_relative_describe(self, vec_world): ...
    def move(self, move_vec) -> None: ...
    def pt_absolute_describe(self, pt_s3d): ...
    def vec_absolute_describe(self, vec_s3d): ...
    def pt_transform(self, to_s3d, pt): ...
    def pts_transform(self, to_s3d, pts): ...
    def to_dict(self): ...
    def from_dict(dict): ...
    def get_reverse(self): ...
    @classmethod
    def by3pt(cls, cen, pt_on_x, pt_maybeon_y): ...
