def volume(length,width,height):
    return width*length*height
def surface_area(length,width,height):
    return 2*((width*length)+(length*height)+(height*width))
def space_diagonal(length,width,height):
    return ((width**2)+(length**2)+(height**2))**0.5
def find_length(space_diagonal,width,height):
    return ((space_diagonal**2)-(width**2)-(height**2))**0.5
def find_width(space_diagonal,length,height):
    return ((space_diagonal**2)-(length**2)-(height**2))**0.5
def find_height(space_diagonal,length,width):
    return ((space_diagonal**2)-(length**2)-(width**2))**0.5