# Stub file for type hints

import os
import shutil
import zipfile
import tarfile
from typing import Callable as _Callable, Optional as _Optional, List as _List
from datetime import datetime as _datetime, timedelta as _timedelta, timezone as _timezone

reserve_days: int: ...
dt: _datetime: ...
files_path: str: ...
sizes_threshold: int: ...
files_path: str: ...
file_zip_filename: str: ...
filename_startswith: str: ...
filename_endswith: str: ...
file_sync_del: bool: ...
zips_path: str: ...
class Files:
    @staticmethod
    def read_file(*args, **kwargs): ...
    @staticmethod
    def write_file(*args, **kwargs): ...
    @staticmethod
    def copy_file(*args, **kwargs): ...
    @staticmethod
    def move_file(*args, **kwargs): ...
    @staticmethod
    def delete_file(*args, **kwargs): ...
    @staticmethod
    def create_directory(*args, **kwargs): ...
    @staticmethod
    def delete_directory(*args, **kwargs): ...
    @staticmethod
    def compress_to_zip(*args, **kwargs): ...
    @staticmethod
    def extract_zip(*args, **kwargs): ...
    @staticmethod
    def compress_to_tar(*args, **kwargs): ...
    @staticmethod
    def extract_tar(*args, **kwargs): ...
    @staticmethod
    def list_files(*args, **kwargs): ...
    @staticmethod
    def get_file_size(*args, **kwargs): ...
    @staticmethod
    def get_directory_size(*args, **kwargs): ...
    @staticmethod
    def reserve_days_of_files(*args, **kwargs): ...
    @staticmethod
    def scan_directory_files(*args, **kwargs): ...
    @staticmethod
    def roll_files_for_reserve_sizes(*args, **kwargs): ...
    @staticmethod
    def zip_files_by_filename(*args, **kwargs): ...

