# -*- coding: utf-8 -*-
"""
QtNetwork module provides classes and functions for network communication.
"""
from PyQt5.QtNetwork import (
    QAbstractNetworkCache,
    QAbstractSocket,
    QAuthenticator,
    # QDnsDomainNameRecord,
    # QDnsHostAddressRecord,
    # QDnsLookup,
    # QDnsMailExchangeRecord,
    # QDnsServiceRecord,
    # QDnsTextRecord,
    QHostAddress,
    QHostInfo,
    QHttpMultiPart,
    QHttpPart,
    QLocalServer,
    QLocalSocket,
    QNetworkAccessManager,
    QNetworkAddressEntry,
    QNetworkCacheMetaData,
    QNetworkConfiguration,
    QNetworkConfigurationManager,
    QNetworkCookie,
    QNetworkCookieJar,
    QNetworkDiskCache,
    QNetworkInterface,
    QNetworkProxy,
    QNetworkProxyFactory,
    QNetworkProxyQuery,
    QNetworkReply,
    QNetworkRequest,
    QNetworkSession,
    QSsl,
    QSslCertificate,
    # QSslCertificateExtension,
    QSslCipher,
    QSslConfiguration,
    # QSslEllipticCurve,
    QSslError,
    QSslKey,
    # QSslPreSharedKeyAuthenticator,
    QSslSocket,
    QTcpServer,
    QTcpSocket,
    QUdpSocket,
)
