# Generated by Django 3.2 on 2021-05-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favicon', '0003_site_manager'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='faviconimg',
            constraint=models.UniqueConstraint(fields=('faviconFK', 'size', 'rel'), name='favicon_size_rel_unique'),
        ),
    ]
