#+title: bisos.vagrantBaseBoxes: Facilities for Creating and Managing Vagrant Packer Base Boxes


|----------------------+------------------------------------------------------------------|
| ~Blee Panel Controls~: | [[elisp:(show-all)][Show-All]] : [[elisp:(org-shifttab)][Overview]] : [[elisp:(progn (org-shifttab) (org-content))][Content]] : [[elisp:(delete-other-windows)][(1)]] : [[elisp:(progn (save-buffer) (kill-buffer))][S&Q]] : [[elisp:(save-buffer)][Save]]  : [[elisp:(kill-buffer)][Quit]]  : [[elisp:(bury-buffer)][Bury]] |
| ~Panel Links~:         | [[file:./panels/bisos.facter/_nodeBase_/fullUsagePanel-en.org][Repo Blee Panel]] --  [[file:/bisos/git/auth/bxRepos/bisos-pip/facter/panels/bisos.facter/_nodeBase_/fullUsagePanel-en.org][Blee Panel]]                                                |
| ~See Also~:            | [[https://pypi.org/project/bisos.facter][At PYPI]] : [[https://github.com/bisos-pip/pycs][bisos.PyCS]]                                             |
|----------------------+------------------------------------------------------------------|


* Overview

/bisos.vagrantBaseBoxes/ provides various facilities for creation and management of
Vagrant Packer Base Boxes.

/bisos.vagrantBaseBoxes/ is a python package that uses the [[https://github.com/bisos-pip/pycs][PyCS-Framework]] for its
implementation. It is a BISOS-Capability and a Standalone-BISOS-Package.

Much of /bisos.vagrantBaseBoxes/ is based on https://github.com/rgl/debian-vagrant
but our general data driven approach is different.




* Table of Contents     :TOC:
- [[#overview][Overview]]
- [[#about-vagrantbaseboxes-data-packer-base-box-specifications][About vagrantBaseBoxes Data (packer base box specifications)]]
- [[#part-of-bisos-----bystar-internet-services-operating-system][Part of BISOS --- ByStar Internet Services Operating System]]
- [[#bisosvagrantbaseboxes-as-a-standalone-piece-of-bisos][bisos.vagrantBaseBoxes as a Standalone Piece of BISOS]]
- [[#installation][Installation]]
  - [[#installation-with-pip][Installation With pip]]
  - [[#installation-with-pipx][Installation With pipx]]
- [[#usage][Usage]]
  - [[#first-install-the-packer-box-specifications][First Install the packer box specifications.]]
  - [[#vagrantboxproccs-menu][vagrantBoxProc.cs Menu]]
- [[#support][Support]]
- [[#planned-improvements][Planned Improvements]]

* About vagrantBaseBoxes Data (packer base box specifications)


/bisos.vagrantBaseBoxes/ is data driven. By itself it is useless. It operates on
well structured directories which contain packer base box specifications.

In BISOS, the packer base box specifications are in the form of a
BISOS Repo Object (BRO). The github url for the BRO is:

[[https://github.com/bxObjects/bro_vagrantDebianBaseBoxes]]

In BISOS, the defaults are:

#+begin_src bash
cd /bisos/git/bxRepos/bxObjects
git clone https://github.com/bxObjects/bro_vagrantDebianBaseBoxes.git
#+end_src

You can clone that repo anywhere and then just adjust the command line path to it.

* Part of BISOS --- ByStar Internet Services Operating System

Layered on top of Debian, *BISOS*: (By* Internet Services Operating System) is a
unified and universal framework for developing both internet services and
software-service continuums that use internet services. See [[https://github.com/bxGenesis/start][Bootstrapping
ByStar, BISOS and Blee]] for information about getting started with BISOS.\\
*BISOS* is a foundation for *The Libre-Halaal ByStar Digital Ecosystem* which is
described as a cure for losses of autonomy and privacy in a book titled: [[https://github.com/bxplpc/120033][Nature
of Polyexistentials]]

* bisos.vagrantBaseBoxes as a Standalone Piece of BISOS

bisos.vagrantBaseBoxes is a standalone piece of BISOS. It can be used as a self-contained
Python package separate from BISOS. Follow the installation and usage
instructions below for your own use.


* Installation

The sources for the bisos.vagrantBaseBoxes pip package are maintained at:
https://github.com/bisos-pip/vagrantBaseBoxes.

The bisos.vagrantBaseBoxes pip package is available at PYPI as
https://pypi.org/project/bisos.vagrantBaseBoxes

You can install bisos.vagrantBaseBoxes with pip or pipx.

** Installation With pip

If you need access to bisos.vagrantBaseBoxes as a python module, you can install it with pip:

#+begin_src bash
pip install bisos.vagrantBaseBoxes
#+end_src

** Installation With pipx

If you only need access to bisos.vagrantBaseBoxes on command-line, you can install it with pipx:

#+begin_src bash
pipx install bisos.vagrantBaseBoxes
#+end_src

The following commands are made available:
- vagrantBaseBoxes-sbom.cs  (Software Bill of Material)
- vagrantBoxProc.cs

* Usage

** First Install the packer box specifications.

Clone the packer box specifications somewhere. Perhaps in your home directory.

#+begin_src bash
git clone https://github.com/bxObjects/bro_vagrantDebianBaseBoxes.git
#+end_src


** vagrantBoxProc.cs Menu

Run:

#+begin_src bash
vagrantBoxProc.cs
#+end_src


* Support

For support, criticism, comments and questions; please contact the
author/maintainer\\
[[http://mohsen.1.banan.byname.net][Mohsen Banan]] at:
[[http://mohsen.1.banan.byname.net/contact]]


* Planned Improvements

- Fully absorb all of lcaVagrantXX.sh

