# Generated by Django 5.2.4 on 2025-07-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='native',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
