# coding: utf-8

"""
    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import circle.web3.user_controlled_wallets
from circle.web3.user_controlled_wallets.models.sca_core import ScaCore  # noqa: E501
from circle.web3.user_controlled_wallets.rest import ApiException

class TestScaCore(unittest.TestCase):
    """ScaCore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScaCore(self):
        """Test ScaCore"""
        # inst = ScaCore()

if __name__ == '__main__':
    unittest.main()
