# coding: utf-8

"""
    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import circle.web3.user_controlled_wallets
from circle.web3.user_controlled_wallets.api.social_email_authentication_api import SocialEmailAuthenticationApi  # noqa: E501
from circle.web3.user_controlled_wallets.rest import ApiException


class TestSocialEmailAuthenticationApi(unittest.TestCase):
    """SocialEmailAuthenticationApi unit test stubs"""

    def setUp(self):
        self.api = circle.web3.user_controlled_wallets.api.social_email_authentication_api.SocialEmailAuthenticationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_device_token_email_login(self):
        """Test case for create_device_token_email_login

        Get a deviceToken to log in with email OTP  # noqa: E501
        """
        pass

    def test_create_device_token_social_login(self):
        """Test case for create_device_token_social_login

        Get deviceToken to perform social login  # noqa: E501
        """
        pass

    def test_refresh_user_token(self):
        """Test case for refresh_user_token

        Get a new userToken with the refreshToken  # noqa: E501
        """
        pass

    def test_resend_otp(self):
        """Test case for resend_otp

        Resend an OTP email to the user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
