# coding: utf-8

"""
    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import circle.web3.user_controlled_wallets
from circle.web3.user_controlled_wallets.models.challenges import Challenges  # noqa: E501
from circle.web3.user_controlled_wallets.rest import ApiException

class TestChallenges(unittest.TestCase):
    """Challenges unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Challenges
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Challenges`
        """
        model = circle.web3.user_controlled_wallets.models.challenges.Challenges()  # noqa: E501
        if include_optional :
            return Challenges(
                data = circle.web3.user_controlled_wallets.models.challenges_data.Challenges_data(
                    challenges = [
                        circle.web3.user_controlled_wallets.models.challenge.Challenge(
                            id = 'c4d1da72-111e-4d52-bdbf-2e74a2d803d5', 
                            correlation_ids = ["54399e5a-1bf6-4921-9559-10c1115678cd"], 
                            error_code = 155121, 
                            error_message = 'challenge expired', 
                            status = 'PENDING', 
                            type = 'SET_PIN', )
                        ], )
            )
        else :
            return Challenges(
                data = circle.web3.user_controlled_wallets.models.challenges_data.Challenges_data(
                    challenges = [
                        circle.web3.user_controlled_wallets.models.challenge.Challenge(
                            id = 'c4d1da72-111e-4d52-bdbf-2e74a2d803d5', 
                            correlation_ids = ["54399e5a-1bf6-4921-9559-10c1115678cd"], 
                            error_code = 155121, 
                            error_message = 'challenge expired', 
                            status = 'PENDING', 
                            type = 'SET_PIN', )
                        ], ),
        )
        """

    def testChallenges(self):
        """Test Challenges"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
