
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-07-08T10:25:58-0400",
 "dirty": true,
 "error": null,
 "full-revisionid": "bff1f2d987207adc30668ef20bf15404de266a02",
 "version": "2.65.0rc10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
