from _typeshed import Incomplete

class Polyline:
    pts: Incomplete
    def __init__(self, pts) -> None: ...
    def is_closed(self): ...
    def get_poly(self): ...
    def get_aabb(self): ...
    def get_area(self): ...
    def get_center(self): ...
    def get_convex_hull(self) -> None: ...
