# This file was auto-generated by Fern from our API Definition.

import typing

WorkflowTaskStepKind = typing.Union[
    typing.Literal[
        "video",
        "image",
        "audio",
        "chapters",
        "subtitles",
        "thumbnails",
        "speech",
        "description",
        "nsfw",
        "prompt",
        "outline",
        "http",
        "ingest",
        "workflow",
        "conditions",
    ],
    typing.Any,
]
