# coding: utf-8

"""
    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import circle.web3.developer_controlled_wallets
from circle.web3.developer_controlled_wallets.models.estimate_contract_execution_transaction_fee_request import EstimateContractExecutionTransactionFeeRequest  # noqa: E501
from circle.web3.developer_controlled_wallets.rest import ApiException

class TestEstimateContractExecutionTransactionFeeRequest(unittest.TestCase):
    """EstimateContractExecutionTransactionFeeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test EstimateContractExecutionTransactionFeeRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EstimateContractExecutionTransactionFeeRequest`
        """
        model = circle.web3.developer_controlled_wallets.models.estimate_contract_execution_transaction_fee_request.EstimateContractExecutionTransactionFeeRequest()  # noqa: E501
        if include_optional :
            return EstimateContractExecutionTransactionFeeRequest(
                abi_function_signature = 'burn(uint256)', 
                abi_parameters = ["100","1"], 
                call_data = '0xcdcd77c000000000000000000000000000000000000000000000000000000000000000450000000000000000000000000000000000000000000000000000000000000001', 
                amount = '1.0', 
                blockchain = 'MATIC-AMOY', 
                contract_address = '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', 
                source_address = '0x1bf9ad0cc2ad298c69a2995aa806ee832788218c', 
                wallet_id = 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'
            )
        else :
            return EstimateContractExecutionTransactionFeeRequest(
                contract_address = '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
        )
        """

    def testEstimateContractExecutionTransactionFeeRequest(self):
        """Test EstimateContractExecutionTransactionFeeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
