# coding: utf-8

"""
    Financial Reports API

    API for accessing company filings, financial data, industry classifications, and related information.

    The version of the OpenAPI document: 1.0.0
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from financial_reports_generated_client.api.gics_classifications_api import GICSClassificationsApi


class TestGICSClassificationsApi(unittest.IsolatedAsyncioTestCase):
    """GICSClassificationsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = GICSClassificationsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_industries_list(self) -> None:
        """Test case for industries_list

        List GICS Industries
        """
        pass

    async def test_industries_retrieve(self) -> None:
        """Test case for industries_retrieve

        Retrieve GICS Industry
        """
        pass

    async def test_industry_groups_list(self) -> None:
        """Test case for industry_groups_list

        List GICS Industry Groups
        """
        pass

    async def test_industry_groups_retrieve(self) -> None:
        """Test case for industry_groups_retrieve

        Retrieve GICS Industry Group
        """
        pass

    async def test_sectors_list(self) -> None:
        """Test case for sectors_list

        List GICS Sectors
        """
        pass

    async def test_sectors_retrieve(self) -> None:
        """Test case for sectors_retrieve

        Retrieve GICS Sector
        """
        pass

    async def test_sub_industries_list(self) -> None:
        """Test case for sub_industries_list

        List GICS Sub-Industries
        """
        pass

    async def test_sub_industries_retrieve(self) -> None:
        """Test case for sub_industries_retrieve

        Retrieve GICS Sub-Industry
        """
        pass


if __name__ == '__main__':
    unittest.main()
