# coding: utf-8

"""
    Financial Reports API

    API for accessing company filings, financial data, industry classifications, and related information.

    The version of the OpenAPI document: 1.0.0
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from financial_reports_generated_client.models.paginated_sub_industry_list import PaginatedSubIndustryList

class TestPaginatedSubIndustryList(unittest.TestCase):
    """PaginatedSubIndustryList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedSubIndustryList:
        """Test PaginatedSubIndustryList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedSubIndustryList`
        """
        model = PaginatedSubIndustryList()
        if include_optional:
            return PaginatedSubIndustryList(
                count = 123,
                next = 'http://api.example.org/accounts/?page=4',
                previous = 'http://api.example.org/accounts/?page=2',
                results = [
                    financial_reports_generated_client.models.sub_industry.SubIndustry(
                        code = '', 
                        name = '', 
                        industry = null, )
                    ]
            )
        else:
            return PaginatedSubIndustryList(
                count = 123,
                results = [
                    financial_reports_generated_client.models.sub_industry.SubIndustry(
                        code = '', 
                        name = '', 
                        industry = null, )
                    ],
        )
        """

    def testPaginatedSubIndustryList(self):
        """Test PaginatedSubIndustryList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
