from embeddedML.multiple_linear_regression import MultipleLinearRegression
from embeddedML.simple_linear_regression import SimpleLinearRegression
from embeddedML.polynominal_regression import PolynomialRegression
from embeddedML.logistic_regression import LogisticRegression
from embeddedML.knn import KNN
from embeddedML.naive_bayes import NaiveBayes
from embeddedML.svm import SVM
from embeddedML.k_means import K_Means
from embeddedML.metrics import Metrics
from embeddedML.preprocessing import Preprocessing