# Generated by Django 4.1.5 on 2023-02-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zb_repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(default='', max_length=150, verbose_name='Description'),
        ),
    ]
