# Generated by Django 5.1.5 on 2025-03-31 10:26

import uuid
from django.db import migrations, models





class Migration(migrations.Migration):

    dependencies = [
        ('zb_repository', '0005_alter_category_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID for this category', null=True, verbose_name='UUID'),
        ),
    ]
