# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: t2iapi/basic_requests.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bt2iapi/basic_requests.proto\x12\x06t2iapi\"$\n\x12\x42\x61sicHandleRequest\x12\x0e\n\x06handle\x18\x01 \x01(\t\"\'\n\x15RepeatedHandleRequest\x12\x0e\n\x06handle\x18\x01 \x03(\tB+\n\x1a\x63om.draeger.medical.t2iapiB\rBasicRequestsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 't2iapi.basic_requests_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.draeger.medical.t2iapiB\rBasicRequests'
  _globals['_BASICHANDLEREQUEST']._serialized_start=39
  _globals['_BASICHANDLEREQUEST']._serialized_end=75
  _globals['_REPEATEDHANDLEREQUEST']._serialized_start=77
  _globals['_REPEATEDHANDLEREQUEST']._serialized_end=116
# @@protoc_insertion_point(module_scope)
