# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: t2iapi/metric/types.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19t2iapi/metric/types.proto\x12\rt2iapi.metric*\xe7\x02\n\x13MeasurementValidity\x12\x1e\n\x1aMEASUREMENT_VALIDITY_VALID\x10\x00\x12\'\n#MEASUREMENT_VALIDITY_VALIDATED_DATA\x10\x01\x12,\n(MEASUREMENT_VALIDITY_MEASUREMENT_ONGOING\x10\x02\x12%\n!MEASUREMENT_VALIDITY_QUESTIONABLE\x10\x03\x12,\n(MEASUREMENT_VALIDITY_CALIBRATION_ONGOING\x10\x04\x12 \n\x1cMEASUREMENT_VALIDITY_INVALID\x10\x05\x12!\n\x1dMEASUREMENT_VALIDITY_OVERFLOW\x10\x06\x12\"\n\x1eMEASUREMENT_VALIDITY_UNDERFLOW\x10\x07\x12\x1b\n\x17MEASUREMENT_VALIDITY_NA\x10\x08*^\n\x0eGenerationMode\x12\x18\n\x14GENERATION_MODE_REAL\x10\x00\x12\x18\n\x14GENERATION_MODE_TEST\x10\x01\x12\x18\n\x14GENERATION_MODE_DEMO\x10\x02*d\n\x0fModeOfOperation\x12\x18\n\x14MODE_OF_OPERATION_ON\x10\x00\x12\x19\n\x15MODE_OF_OPERATION_OFF\x10\x01\x12\x1c\n\x18MODE_OF_OPERATION_PAUSED\x10\x02*\xa6\x02\n\x0cMetricStatus\x12&\n\"METRIC_STATUS_PERFORMED_OR_APPLIED\x10\x00\x12(\n$METRIC_STATUS_CURRENTLY_INITIALIZING\x10\x01\x12<\n8METRIC_STATUS_INITIALIZED_BUT_NOT_PERFORMING_OR_APPLYING\x10\x02\x12+\n\'METRIC_STATUS_CURRENTLY_DE_INITIALIZING\x10\x03\x12?\n;METRIC_STATUS_DE_INITIALIZED_AND_NOT_PERFORMING_OR_APPLYING\x10\x04\x12\x18\n\x14METRIC_STATUS_FAILED\x10\x05*q\n\x17MetricDeterminationMode\x12*\n&METRIC_DETERMINATION_MODE_EPISODICALLY\x10\x00\x12*\n&METRIC_DETERMINATION_MODE_PERIODICALLY\x10\x01\x42\x30\n!com.draeger.medical.t2iapi.metricB\x0bMetricTypesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 't2iapi.metric.types_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.draeger.medical.t2iapi.metricB\013MetricTypes'
  _globals['_MEASUREMENTVALIDITY']._serialized_start=45
  _globals['_MEASUREMENTVALIDITY']._serialized_end=404
  _globals['_GENERATIONMODE']._serialized_start=406
  _globals['_GENERATIONMODE']._serialized_end=500
  _globals['_MODEOFOPERATION']._serialized_start=502
  _globals['_MODEOFOPERATION']._serialized_end=602
  _globals['_METRICSTATUS']._serialized_start=605
  _globals['_METRICSTATUS']._serialized_end=899
  _globals['_METRICDETERMINATIONMODE']._serialized_start=901
  _globals['_METRICDETERMINATIONMODE']._serialized_end=1014
# @@protoc_insertion_point(module_scope)
