from openagentkit.core.interfaces import BaseChunker as BaseChunker

class RecursiveTextChunker(BaseChunker):
    def __init__(self, chunk_size: int = 100, separator: str = '\n', size_flexibility: float = 0.2) -> None: ...
    @property
    def chunk_size(self) -> int: ...
    def get_chunks(self, text: str) -> list[str]: ...
