import os

OPENAI_API_KEY=os.getenv("OPENAI_API_KEY")
LLM_PROVIDER=os.getenv("LLM_PROVIDER")
VISION_AGENT_API_KEY=os.getenv("VISION_AGENT_API_KEY")
OPEN_AI_EXTRACTION_MODEL=os.getenv("OPEN_AI_EXTRACTION_MODEL")
OPEN_AI_PARSE_FORMATING_MODEL=os.getenv("OPEN_AI_PARSE_FORMATING_MODEL")

MAX_RETRY=5
ASYNC_OPENAI_RATE_LIMIT=25
ASYNC_OPEN_AI_TIME_PERIOD=60
ASYNC_CONCURRENCY_LIMIT=10
