# Form implementation generated from reading ui file 'select_channel.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_select_channle(object):
    def setupUi(self, select_channle):
        select_channle.setObjectName("select_channle")
        select_channle.resize(677, 500)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(select_channle)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=select_channle)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.checkBox_analog_all = QtWidgets.QCheckBox(parent=select_channle)
        self.checkBox_analog_all.setObjectName("checkBox_analog_all")
        self.horizontalLayout.addWidget(self.checkBox_analog_all)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listWidget_analog = QtWidgets.QListWidget(parent=select_channle)
        self.listWidget_analog.setObjectName("listWidget_analog")
        self.verticalLayout.addWidget(self.listWidget_analog)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=select_channle)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.checkBox_digital_all = QtWidgets.QCheckBox(parent=select_channle)
        self.checkBox_digital_all.setObjectName("checkBox_digital_all")
        self.horizontalLayout_2.addWidget(self.checkBox_digital_all)
        self.checkBox_digital_change = QtWidgets.QCheckBox(parent=select_channle)
        self.checkBox_digital_change.setObjectName("checkBox_digital_change")
        self.horizontalLayout_2.addWidget(self.checkBox_digital_change)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.listWidget_digital = QtWidgets.QListWidget(parent=select_channle)
        self.listWidget_digital.setObjectName("listWidget_digital")
        self.verticalLayout_2.addWidget(self.listWidget_digital)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=select_channle)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(select_channle)
        self.buttonBox.accepted.connect(select_channle.accept) # type: ignore
        self.buttonBox.rejected.connect(select_channle.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(select_channle)

    def retranslateUi(self, select_channle):
        _translate = QtCore.QCoreApplication.translate
        select_channle.setWindowTitle(_translate("select_channle", "Dialog"))
        self.label.setText(_translate("select_channle", "选择模拟量"))
        self.checkBox_analog_all.setText(_translate("select_channle", "全选"))
        self.label_2.setText(_translate("select_channle", "选择开关量"))
        self.checkBox_digital_all.setText(_translate("select_channle", "全选"))
        self.checkBox_digital_change.setText(_translate("select_channle", "仅变位"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    select_channle = QtWidgets.QDialog()
    ui = Ui_select_channle()
    ui.setupUi(select_channle)
    select_channle.show()
    sys.exit(app.exec())
