# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .error import Error
from .links_list import LinksList
from .meta_list import MetaList
from .task import Task


class TaskListResponse(UncheckedBaseModel):
    meta: typing.Optional[MetaList] = None
    data: typing.Optional[typing.List[Task]] = None
    error: typing.Optional[Error] = None
    links: typing.Optional[LinksList] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
