# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Optional
from typing_extensions import Literal

from ..._models import BaseModel
from .function_call import FunctionCall
from .chat_completion_message_tool_call_param import ChatCompletionMessageToolCallParam

__all__ = ["ChatCompletionAssistantMessageParam"]


class ChatCompletionAssistantMessageParam(BaseModel):
    role: Literal["assistant"]
    """The role of the messages author, in this case `assistant`."""

    content: Optional[str] = None
    """The contents of the assistant message."""

    function_call: Optional[FunctionCall] = None
    """Deprecated and replaced by `tool_calls`."""

    name: Optional[str] = None
    """An optional name for the participant."""

    tool_calls: Optional[List[ChatCompletionMessageToolCallParam]] = None
    """The tool calls generated by the model, such as function calls."""
