# Stub file for type hints

import platform
import subprocess
import uuid
import hashlib
from typing import Dict as _Dict, Optional as _Optional

class Devices:
    @staticmethod
    def get_system(*args, **kwargs): ...
    @staticmethod
    def get_node(*args, **kwargs): ...
    @staticmethod
    def get_release(*args, **kwargs): ...
    @staticmethod
    def get_version(*args, **kwargs): ...
    @staticmethod
    def get_machine(*args, **kwargs): ...
    @staticmethod
    def get_processor(*args, **kwargs): ...
    @staticmethod
    def get_system_info(*args, **kwargs): ...
    @staticmethod
    def get_device_mac(*args, **kwargs): ...
    @staticmethod
    def get_windows_machine_guid(*args, **kwargs): ...
    @staticmethod
    def get_linux_machine_id(*args, **kwargs): ...
    @staticmethod
    def get_macos_serial_number(*args, **kwargs): ...
    @staticmethod
    def generate_fingerprint(*args, **kwargs): ...
    @staticmethod
    def get_device_id(*args, **kwargs): ...

