# Stub file for type hints

import time
from datetime import datetime as _datetime, timedelta as _timedelta, timezone as _timezone
from typing import Union as _Union, Optional as _Optional

dt: _datetime: ...
fmt: str: ...
hour: int: ...
minute: int: ...
second: int: ...
fmt: str: ...
days: float: ...
hours: float: ...
minutes: float: ...
seconds: float: ...
days: float: ...
hours: float: ...
minutes: float: ...
seconds: float: ...
class Times:
    @staticmethod
    def get_current_datetime(*args, **kwargs): ...
    @staticmethod
    def format_datetime(*args, **kwargs): ...
    @staticmethod
    def get_num_datetime(*args, **kwargs): ...
    @staticmethod
    def datetime_to_timestamp(*args, **kwargs): ...
    @staticmethod
    def timestamp_to_datetime(*args, **kwargs): ...
    @staticmethod
    def parse_datetime(*args, **kwargs): ...
    @staticmethod
    def add_time(*args, **kwargs): ...
    @staticmethod
    def subtract_time(*args, **kwargs): ...
    @staticmethod
    def time_diff(*args, **kwargs): ...
    @staticmethod
    def convert_timezone(*args, **kwargs): ...
    @staticmethod
    def is_leap_year(*args, **kwargs): ...
    @staticmethod
    def sleep(*args, **kwargs): ...
    @staticmethod
    def get_tomorrow_datetime(*args, **kwargs): ...
    @staticmethod
    def retry(*args, **kwargs): ...
    def risky_operation(self, *args, **kwargs): ...
    def decorator(self, *args, **kwargs): ...
    def wrapper(self, *args, **kwargs): ...

