# coding: utf-8

"""
    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field
from circle.web3.user_controlled_wallets.models.wallet_response_data_wallet import WalletResponseDataWallet

class WalletResponseData(BaseModel):
    """
    WalletResponseData
    """
    wallet: WalletResponseDataWallet = Field(...)
    __properties = ["wallet"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> WalletResponseData:
        """Create an instance of WalletResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of wallet
        if self.wallet:
            _dict['wallet'] = self.wallet.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> WalletResponseData:
        """Create an instance of WalletResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return WalletResponseData.parse_obj(obj)

        _obj = WalletResponseData.parse_obj({
            "wallet": WalletResponseDataWallet.from_dict(obj.get("wallet")) if obj.get("wallet") is not None else None
        })
        return _obj


