# coding: utf-8

"""
    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import circle.web3.developer_controlled_wallets
from circle.web3.developer_controlled_wallets.models.wallets import Wallets  # noqa: E501
from circle.web3.developer_controlled_wallets.rest import ApiException

class TestWallets(unittest.TestCase):
    """Wallets unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Wallets
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Wallets`
        """
        model = circle.web3.developer_controlled_wallets.models.wallets.Wallets()  # noqa: E501
        if include_optional :
            return Wallets(
                data = circle.web3.developer_controlled_wallets.models.wallets_data.Wallets_data(
                    wallets = [
                        null
                        ], )
            )
        else :
            return Wallets(
                data = circle.web3.developer_controlled_wallets.models.wallets_data.Wallets_data(
                    wallets = [
                        null
                        ], ),
        )
        """

    def testWallets(self):
        """Test Wallets"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
