# coding: utf-8

"""
    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import circle.web3.developer_controlled_wallets
from circle.web3.developer_controlled_wallets.models.new_sca_core import NewScaCore  # noqa: E501
from circle.web3.developer_controlled_wallets.rest import ApiException

class TestNewScaCore(unittest.TestCase):
    """NewScaCore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewScaCore(self):
        """Test NewScaCore"""
        # inst = NewScaCore()

if __name__ == '__main__':
    unittest.main()
