# coding: utf-8

"""
    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import circle.web3.developer_controlled_wallets
from circle.web3.developer_controlled_wallets.api.signing_api import SigningApi  # noqa: E501
from circle.web3.developer_controlled_wallets.rest import ApiException


class TestSigningApi(unittest.TestCase):
    """SigningApi unit test stubs"""

    def setUp(self):
        self.api = circle.web3.developer_controlled_wallets.api.signing_api.SigningApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sign_delegate_action(self):
        """Test case for sign_delegate_action

        Sign delegate action  # noqa: E501
        """
        pass

    def test_sign_message(self):
        """Test case for sign_message

        Sign message  # noqa: E501
        """
        pass

    def test_sign_transaction(self):
        """Test case for sign_transaction

        Sign transaction  # noqa: E501
        """
        pass

    def test_sign_typed_data(self):
        """Test case for sign_typed_data

        Sign typed data  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
