# coding: utf-8

"""
    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import circle.web3.developer_controlled_wallets
from circle.web3.developer_controlled_wallets.models.contract_execution_blockchain import ContractExecutionBlockchain  # noqa: E501
from circle.web3.developer_controlled_wallets.rest import ApiException

class TestContractExecutionBlockchain(unittest.TestCase):
    """ContractExecutionBlockchain unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContractExecutionBlockchain(self):
        """Test ContractExecutionBlockchain"""
        # inst = ContractExecutionBlockchain()

if __name__ == '__main__':
    unittest.main()
