from pydantic import BaseModel
from typing import Any

class CollectionCreate(BaseModel):
    collection_schema: dict[str, Any]

class CollectionRename(BaseModel): ...
class CollectionDrop(BaseModel): ...
class CollectionLoad(BaseModel): ...
class VectorAdd(BaseModel): ...
class VectorAddBatch(BaseModel): ...
class VectorUpdate(BaseModel): ...
class VectorSearch(BaseModel): ...
class VectorQuery(BaseModel): ...
class VectorDelete(BaseModel): ...
