from _typeshed import Incomplete
from openagentkit.core.models.tool_responses import CurrentWeather as CurrentWeather, WeatherForecast as WeatherForecast, WeatherResponse as WeatherResponse
from openagentkit.core.tools.base_tool import tool as tool
from typing import Annotated, Literal

logger: Incomplete

def get_weather_data(location: str, days: int, api_key: str) -> dict: ...
def get_location_from_ip() -> str: ...
def extract_current_weather(weather_data: dict) -> CurrentWeather | None: ...
def extract_forecast(weather_data: dict) -> list: ...
@tool
def get_weather_tool(mode: Annotated[Literal['current', 'forecast', 'both'], 'Weather Response mode.'], location: Annotated[str | Literal['Unknown'], 'The location to get the weather forecast for.'], days: Annotated[int | Literal[0], 'The number of days to get the weather forecast for. Maximum of 3']) -> WeatherResponse: ...
