# This file was auto-generated by Fern from our API Definition.

import typing

StyleGuideCategory = typing.Union[
    typing.Literal[
        "punctuation", "capitalization", "grammar_and_usage", "numbers_and_dates", "formatting_and_structure", "other"
    ],
    typing.Any,
]
