
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-07-04T09:56:23+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "0cd9070c8f70b81d94ba70e79696674255953af9",
 "version": "0.8.0.post0.dev36"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
