# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .theia_output import TheiaOutput
from .workflow_status import WorkflowStatus


class WorkflowStatusResponse(UniversalBaseModel):
    workflow_id: str
    status: WorkflowStatus
    error_message: typing.Optional[str] = None
    result: typing.Optional[TheiaOutput] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
